/* Copyright 2022 Sagacity Solutions Inc. All right reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifdef COMBO_ENABLE

#include QMK_KEYBOARD_H

#include "sjb.h"

#define SJB_DEFINE_KEY(name, ...) const uint16_t PROGMEM combo_##name[] = {__VA_ARGS__, COMBO_END}

#define SJB_COMBO(name, action) COMBO(combo_##name, action)

SJB_DEFINE_KEY(CK_LBOOT,  HRM_COL1(LEFT_QW_ROW_1), HRM_COL5(LEFT_QW_ROW_1));
SJB_DEFINE_KEY(CK_RBOOT,  HRM_COL1(RIGHT_QW_ROW_1), HRM_COL5(RIGHT_QW_ROW_1));
SJB_DEFINE_KEY(CK_POWER,  HRM_COL1(LEFT_QW_ROW_1), HRM_COL1(LEFT_QW_ROW_3));

#ifdef LAYER_LOCK_ENABLE
SJB_DEFINE_KEY(CK_LAYER_LOCK, HRM_COL5(LEFT_QW_ROW_2), HRM_COL1(RIGHT_QW_ROW_2));
#endif

#ifdef KEY_LOCK_ENABLE
SJB_DEFINE_KEY(CK_KEY_LOCK, HRM_COL4(LEFT_QW_ROW_2), HRM_COL2(RIGHT_QW_ROW_2));
#endif

#ifdef CAPS_WORD_ENABLE
//  left-shift + right-shift
SJB_DEFINE_KEY(CK_CWTOGG,   HRM_COL4(LEFT_QW_ROW_2), HRM_COL2(RIGHT_QW_ROW_2));
#endif

#ifdef REPEAT_KEY_ENABLE
SJB_DEFINE_KEY(CK_KEY_LREP, HRM_COL4(LEFT_QW_ROW_2), HRM_COL3(LEFT_QW_ROW_2));
SJB_DEFINE_KEY(CK_KEY_RREP, HRM_COL2(RIGHT_QW_ROW_2), HRM_COL3(RIGHT_QW_ROW_2));
#endif

#ifndef ACHORDION_ENABLE

#ifdef CB_LLEADER
SJB_DEFINE_KEY(CK_LSFT, CB_LLEADER, HRM_COL4(LEFT_QW_ROW_2));
SJB_DEFINE_KEY(CK_LALT, CB_LLEADER, HRM_COL1(LEFT_QW_ROW_2));
SJB_DEFINE_KEY(CK_LGUI, CB_LLEADER, HRM_COL2(LEFT_QW_ROW_2));
SJB_DEFINE_KEY(CK_LCTL, CB_LLEADER, HRM_COL3(LEFT_QW_ROW_2));
SJB_DEFINE_KEY(CK_LCG , CB_LLEADER, HRM_COL3(LEFT_QW_ROW_2), HRM_COL2(LEFT_QW_ROW_2));
SJB_DEFINE_KEY(CK_LCA , CB_LLEADER, HRM_COL3(LEFT_QW_ROW_2), HRM_COL1(LEFT_QW_ROW_2));
SJB_DEFINE_KEY(CK_LGA , CB_LLEADER, HRM_COL2(LEFT_QW_ROW_2), HRM_COL1(LEFT_QW_ROW_2));
SJB_DEFINE_KEY(CK_LCGA, CB_LLEADER, HRM_COL3(LEFT_QW_ROW_2), HRM_COL2(LEFT_QW_ROW_2), HRM_COL1(LEFT_QW_ROW_2));
#endif

#ifdef CB_RLEADER
SJB_DEFINE_KEY(CK_RSFT, CB_RLEADER, HRM_COL2(RIGHT_QW_ROW_2));
SJB_DEFINE_KEY(CK_RALT, CB_RLEADER, HRM_COL5(RIGHT_QW_ROW_2));
SJB_DEFINE_KEY(CK_RGUI, CB_RLEADER, HRM_COL4(RIGHT_QW_ROW_2));
SJB_DEFINE_KEY(CK_RCTL, CB_RLEADER, HRM_COL3(RIGHT_QW_ROW_2));
SJB_DEFINE_KEY(CK_RCG , CB_RLEADER, HRM_COL3(RIGHT_QW_ROW_2), HRM_COL4(RIGHT_QW_ROW_2));
SJB_DEFINE_KEY(CK_RCA , CB_RLEADER, HRM_COL3(RIGHT_QW_ROW_2), HRM_COL5(RIGHT_QW_ROW_2));
SJB_DEFINE_KEY(CK_RGA , CB_RLEADER, HRM_COL4(RIGHT_QW_ROW_2), HRM_COL5(RIGHT_QW_ROW_2));
SJB_DEFINE_KEY(CK_RCGA, CB_RLEADER, HRM_COL3(RIGHT_QW_ROW_2), HRM_COL4(RIGHT_QW_ROW_2), HRM_COL5(RIGHT_QW_ROW_2));
#endif

#endif

#ifdef SB_LAYER_SWITCH_COMBO_KEY

#ifdef CB_LLEADER
SJB_DEFINE_KEY(CK_TG_NUM,   CB_LLEADER, HRM_COL5(LEFT_QW_ROW_2));
#endif

#ifdef CB_RLEADER
SJB_DEFINE_KEY(CK_TG_MOUSE, CB_RLEADER, HRM_COL1(RIGHT_QW_ROW_2));
#endif

#endif

combo_t key_combos[] = {
    SJB_COMBO(CK_LBOOT, QK_BOOT),
    SJB_COMBO(CK_RBOOT, QK_BOOT),
    SJB_COMBO(CK_POWER, KC_PWR),

#ifdef LAYER_LOCK_ENABLE
    SJB_COMBO(CK_LAYER_LOCK, SB_LLOCK),
#endif

#ifdef KEY_LOCK_ENABLE
    SJB_COMBO(CK_KEY_LOCK,   QK_LOCK),
#endif

#ifdef CAPS_WORD_ENABLE
    SJB_COMBO(CK_CWTOGG, CW_TOGG),
#endif

#ifdef REPEAT_KEY_ENABLE
    SJB_COMBO(CK_KEY_RREP,   QK_AREP),
    SJB_COMBO(CK_KEY_LREP,   QK_REP),
#endif

#ifndef ACHORDION_ENABLE

#ifdef CB_LLEADER
    SJB_COMBO(CK_LSFT, OSM(MOD_LSFT)),
    SJB_COMBO(CK_LALT, OSM(MOD_LALT)),
    SJB_COMBO(CK_LGUI, OSM(MOD_LGUI)),
    SJB_COMBO(CK_LCTL, OSM(MOD_LCTL)),
    SJB_COMBO(CK_LCG , OSM(MOD_LCTL | MOD_LGUI)),
    SJB_COMBO(CK_LCA , OSM(MOD_LCTL | MOD_LALT)),
    SJB_COMBO(CK_LGA , OSM(MOD_LGUI | MOD_LALT)),
    SJB_COMBO(CK_LCGA, OSM(MOD_LCTL | MOD_LGUI | MOD_LALT)),
#endif

#ifdef CB_RLEADER
    SJB_COMBO(CK_RSFT, OSM(MOD_LSFT)),
    SJB_COMBO(CK_RALT, OSM(MOD_LALT)),
    SJB_COMBO(CK_RGUI, OSM(MOD_RGUI)),
    SJB_COMBO(CK_RCTL, OSM(MOD_RCTL)),
    SJB_COMBO(CK_RCG , OSM(MOD_RCTL | MOD_RGUI)),
    SJB_COMBO(CK_RCA , OSM(MOD_RCTL | MOD_LALT)),
    SJB_COMBO(CK_RGA , OSM(MOD_RGUI | MOD_LALT)),
    SJB_COMBO(CK_RCGA, OSM(MOD_RCTL | MOD_RGUI | MOD_LALT)),
#endif

#endif

#ifdef SB_LAYER_SWITCH_COMBO_KEY

#ifdef CB_LLEADER
    SJB_COMBO(CK_TG_NUM, TG(_NUMPAD)),
#endif

#ifdef CB_RLEADER
    SJB_COMBO(CK_TG_MOUSE, TG(_MOUSE)),
#endif

#endif

};

#endif
